import CustomCursor from "./components/Cursor/Cursor";
import "./globals.css";

export const metadata = {
  title: "Fian",
  description: "Generated by fian siburian",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="cursor-none">
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
